#!/bin/bash
echo "hey whatsup"
BRANCHNAME=$(git rev-parse --abbrev-ref HEAD)
# if [ "$BRANCHNAME" == "release" ];then
#	curl "http://localhost:8080/job/M1-release/build?token=ahmad" -u "ahmad:ahmad"
#elif [ "$BRANCHNAME" == "dev" ];then
	curl "http://104.236.196.86:8080/job/M3-Dev/build?token=ahmad" -u "manasee:manasee"
#fi

echo "Build triggered successfully on branch: $BRANCHNAME"
